### PR TITLE
Saddle Recipe

### PR DESCRIPTION
**Pull request by OtonashiRyuugen**
### Description
Added a custom recipe for crafting a saddle. Created with the intention of making a loading class to load many crafting recipes (to be possibly integrated later with the teleport pads)

crafting recipe is 
```
   *
   ***
   &*&
```

where leather is *
and iron ingots are &

### Related Issues/PRs
no known Issues

### CODE REVIEW

**Comment by JamesJ** [comment]
@OtonashiRyuugen what the fuck?
https://github.com/OtonashiRyuugen/mcsurvival/blob/5e1c30f3f66abf2602f33563e5b7ea8d633b6150/src/main/java/me/theminecoder/mcsurvival/recipes/saddle.java

**Comment by Lemons** [comment]
Make sure to ALWAYS comment on your imports, ok? Thanks!

**Comment by Phineas** [comment]
crying

**Comment by OtonashiRyuugen** [comment]
@JamesJ , whys the wtf for?

@Lemons , i will make sure to do that from now on

@Phineas , why are you crying, i cant tell if your sad or happy crying xD

**Comment by JamesJ** [comment]
@OtonashiRyuugen look at the code.
That won't even compile lmfao. Did you write that from GitHub's "New File" or from an IDE lol.
I haven't seen code this bad in a long time. 😆

**Comment by OtonashiRyuugen** [comment]
@JamesJ , sorry, i dont see whats wrong with it...... i am quite new to java (as you can probably tell), as i mainly work in c or r languages. Thanks for giving it to me as it is, and any advice for moving it in the right direction would be great. 

P.S. i was using atom.

**Comment by JamesJ** [comment]
Well please use an IDE - such as Eclipse or IntelliJ..
As https://github.com/OtonashiRyuugen/mcsurvival/blob/5e1c30f3f66abf2602f33563e5b7ea8d633b6150/src/main/java/me/theminecoder/mcsurvival/recipes/saddle.java
this wont even compile... let alone run..

**Comment by OtonashiRyuugen** [comment]
all right, thanks for the pointer... ill get onto it as soon as i can. thanks 😄

**Comment by theminecoder** [comment]
Going to close this due to inactivity.

**Pull request closed without merging**
